### ISSUE TITLE
add new keyword for OPDINDEX or OPDSLICE

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#297]
Right now if you specify which OPD to use (in a multi-OPD data cube), it gets added into the FITS header as part of a string in the PUPILOPD keyword, e.g. `PUPILOPD = 'OPD_RevW_ote_for_NIRCam_predicted.fits.gz slice 7'`. It would probably be more convenient and less confusing to users to have separate keywords. More like this:
```
PUPILOPD = 'OPD_RevW_ote_for_NIRCam_predicted.fits.gz'
OPDSLICE = 7
```

Suggested in #292, commented on in #293 but decided to make this a separate issue.

**Comment by shanosborne** [comment]
It looks like the `PUPILOPD` keyword is set in poppy/instrument.py rather than in webbpsf. I would assume that poppy would also benefit from having these keywords separated, unless you can think of a reason why we would only want to do this for webbpsf.

Also continuing the discussion of what version this new webbpsf release should be, wouldn't this update to the `PUPILOPD` keyword make this release not backwards compatible (assuming someone out there is pulling the slice information from the string)?

**Comment by mperrin** [comment]
We could add an additional keyword without changing the value of the current one perhaps?

Agreed this fix goes in poppy/instrument.py

**Comment by shanosborne** [comment]
That sounds good to me. Maybe something like `OPD_FILE`
