### ISSUE TITLE
Add NIRCam weak lens +4 filter coating throughput

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/webbpsf#306]
Currently when creating a PSF using NIRCam's weak lens +4, a user must also manually set the filter to F212N in order to simulate the filter coating that is on WLP4. However, the filter coating on WLP4 has a slightly different bandpass than the F212N filter, which should be used instead. Attached is the weak lens throughput curve from the UofA team.

[WLp4_Transmission_2014.txt](https://github.com/spacetelescope/webbpsf/files/3278645/WLp4_Transmission_2014.txt)

**Comment by mperrin** [comment]
Here's a plot of that transmission curve, converted into the FITS table format that WebbPSF uses, and plotted for comparison with F212N. 

![Unknown-3](https://user-images.githubusercontent.com/1151745/61829152-53dd7480-ae36-11e9-8c46-36263ba589a6.png)

**Comment by mperrin** [comment]
@bhilbert4 I've added the WLP4 filter file to our data source, so it will be included in the next webbpsf release (very soon). Let me know if you would like to test using it before then.

Right now, this is simplified and treated as just another selectable filter, without any extra logic to enforce that it's only available for use with the WLP4 lens itself, nor that if you're using WLP4 lens you have no choice but to use this filter. In general WebbPSF assumes the user knows enough to be responsible for knowing if they're simulating a sensible case or not. We may add more sanity-check logic in the future but it's not top priority now. 

Note also, as always WebbPSF outputs its PSFs to total intensity=1. So switching a PSF calculation from F212N to WLP4 won't result in there being more total counts in the PSF; it'll just have a different normalization factor in the calculation to achieve sum=1 in the output PSF. This is presumably what you expect, and I'm just mentioning it for completeness.

**Comment by bhilbert4** [comment]
Looks good. I'm happy to test if you'd like me to, but I'm also happy to wait for the release.

**Comment by mperrin** [comment]
No urgent need for you to test, I think. Thanks

**Comment by mperrin** [comment]
Update - turns out this is actually in Pandeia now too, so I can switch to getting this filter transmission from the Pandeia ref data consistently with all the others. Nice. Thanks to @ariedel for help with that.

**Comment by ariedel** [comment]
For what it's worth, when we implemented the NIRCam SW Time Series mode, we had discussions about whether the filter coating of the WLP4 lens should be called F212N2 (we decided to call it wlp4 internally and display the F212N2 name on the website)

**Comment by mperrin** [comment]
Closely related to this issue: Now that WLP4 is available as a filter, WebbPSF ought to realize that selecting that filter requires the +4 waves defocus to be present in the pupil, and vice versa. Similarly, it should be possible to select `filter = "WLP4"` and` pupil_mask = "WLP8"`, and actually end up with the +12 defocus.  This simulates with more fidelity the arrangement of optics between the filter and pupil wheels of NIRCam, something we have until now sort of glossed over here. 

Implementing this somewhat complicates the logic for weak lens selection (since we will maintain for back-compatibility the historical way of selecting this all with pupil_mask, but now there's also this new way that uses both pupil_mask and filter). However, this is still worth it since it turns out to help with the integration of weak lens PSFs into MIRAGE; MIRAGE tests both the pupil and filter keywords in FITS headers for matches when selecting PSFs, so it helps for the WebbPSF outputs to better model what's in each wheel.

**Comment by mperrin** [comment]
This was done a while ago (see above commits) but we overlooked closing the issue then. Closing now.
