### ISSUE TITLE
Update Dev release docs

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#336]
Update Dev release docs:

- [x] Link data on box 

~~- [ ] Add warning about PyPI releases (they can not be undone)~~

**Comment by mperrin** [comment]
@robelgeda and an issue you self assigned last year to update some dev docs. Do you have any intent to follow up on this? Worth keeping this issue open or not at this point?

**Comment by robelgeda** [comment]
Yes I do, I thought this ticket be the last one since it would help to write the procedure as we go through them.

**Comment by mperrin** [comment]
@ojustino here is a (pretty vague) issue which Robel self-assigned. I'm inclined to just close this with no further action, since I'm not sure what exactly Robel intended with this. But if you think it's worth doing any work to update the dev release notes, let me know; otherwise I'll go ahead and close this.

**Comment by robelgeda** [comment]
Just saw this in email. This was a ticket to add to the instructions that we need to upload to box. Since that is already in the docs and since we no longer wish to upload things manually to PyPi, this ticket can be closed.
