### ISSUE TITLE
Jitter for coronographic observations

### ISSUE THREAD

**Issue by ccossou** [spacetelescope/webbpsf#376]
Context: I'm doing MIRI Coronograph runs with webbpsf.

As far as I understand, jitter is modeled as a simple convolution by a gaussian (of 7mas by default). This is not correct for a coronograph (at least not the 4 coronograph of MIRI but I'm pretty sure this is also valid for any coronograph).

While this works for imager observations, a coronograph is not linear and this convolution doesn't make any sense (I discussed this with Anthony Boccaletti and Pierre Baudoz, the local experts on MIRI coronographs here in France). 

Could jitter be deactivated by default for coronograph and a warning displayed if anyone try to use that functionality?

I don't expect a "solution" because this is far from trivial, but I just wanted to raise this issue. 

I run my simulations by forcing jitter to NONE to avoid that convolution, even though there's no obvious replacement.

(I couldn't find a JIRA section for webbpsf, hence why I submit an issue to github)

**Comment by JarronL** [comment]
Perhaps you could run some MIRI 4QPM simulations with `jitter=None` with a number of PSF offsets such that the offset distribution is representative of a 7mas jitter model, then take the average. Then back out the convolution kernel that would be necessary to get that result if you started from the perfectly centered `jitter=None` PSF.

**Comment by ccossou** [comment]
My point was not really to find a way to simulate jitter, but rather deactivate this webbpsf functionality for all coronagraphic images because it doesn't make any sense.

**Comment by mperrin** [comment]
Hi @ccossou, for sure you’re correct that the convolution model doesn’t rigorously apply to coronagraphic images with the star occulted by the central spot or by the FQPM. But on the other had it _does_ apply to off-axis coronagraphic PSFs, for instance the PSF of a companion. Both cases are valid. On the other hand an off axis companion right on one of the FQPM quadrant edges is also not a simple Gaussian convolution. And so on. For this reason it’s not obvious how best to make a simple automatic switch such as you describe. It could be done but it’s a bit subtle. 

In part because of that, we haven’t prioritized adding this in WebbPSF as an automatic feature. Also as you correctly point out, there isn’t an easy replacement. It is a much more computationally expensive approach to do many simulations at slightly offset points and coadd the results. 
In any case, with coronagraph simulations we can generally expect most users to be experts who have a good understanding of these factors, like you. The option to switch off the jitter just like you’ve done is the recommended approach for cases for which you want to avoid the convolution, yes.

**Comment by mperrin** [comment]
I should add, if you want to take a try at developing code to switch the convolution off automatically for the relevant subset of calculations, please do. We’re always very grateful for any code contributions and improvements via pull requests on here! Thanks for raising this point in conversation.

**Comment by ccossou** [comment]
Thanks for your comments. To be honest, I did not consider the case of an off-axis source. 

I don't have time at the moment to do this pull request but will keep that in mind in the future. 

Thanks both for your time. Closing.
