### ISSUE TITLE
Update install instructions for new conda environment 

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/webbpsf#379]
The first command recommended to create a new webbpsf environment wreaks havoc with conda 
channels (https://webbpsf.readthedocs.io/en/latest/installation.html, under 'Installing with conda'):

$ conda config --add channels http://ssb.stsci.edu/astroconda
$ conda create -n webbpsf-env webbpsf
$ source activate webbpsf-env
-----------------------------

After running the above 'conda config' command, I am no longer able to create any new conda environments,
because this moves the astroconda channel priority to highest priority:

$ conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'
--add channels 'http://ssb.stsci.edu/astroconda'   # highest priority

----------------------------
When I try to install any new conda environment, I get this, e.g.:

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::asn1crypto-1.4.0-pyh9f0ad1d_0'.
FileNotFoundError(2, "No such file or directory: '/Users/pogle/miniconda3/bin/python3.7'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/Users/pogle/miniconda3/bin/python3.7'")
--------------------------

This was fixed by doing this:

conda config --append channels http://ssb.stsci.edu/astroconda

$ conda config --get channels
--add channels 'http://ssb.stsci.edu/astroconda'   # lowest priority
--add channels 'defaults'
--add channels 'conda-forge'   # highest priority
---------------------------

Recommendation:
Change the installation instructions to this:

$ conda config --append channels http://ssb.stsci.edu/astroconda
$ conda create -n webbpsf-env webbpsf
$ source activate webbpsf-env

i.e., Change 'add' to 'append' in first line of the instructions

**Comment by PatrickOgle** [comment]
@mperrin :  This issue is important to resolve soon, for JWST Cycle1 proposers.

**Comment by mperrin** [comment]
@shanosborne can you take a look at this one please - I think you may understand the conda infrastructure a little better than I do. And if there's a preferred way to specify this in the install instructions you may want to make sure it's consistent across the various INS tools. 

Thanks @PatrickOgle

**Comment by shanosborne** [comment]
Switching our recommended command from `add` to `append` seems fine to me. `Conda` will search for a package in each of the channels going from the highest priority to the lowest priority, but since `webbpsf` only exists in the `astroconda` channel, it should always find the right package. We could give people the option of choosing `add` or `append` in our docs but that may be unnecessarily complicated.

Also, since that `conda config` line of code comes from the section of our installation docs that are intended for a user who doesn't want to install all of `astroconda`, but instead only wants to install `webbpsf`, it makes sense that they wouldn't want the `astroconda` channel to be the highest priority and `append` would be better.

I will note that currently the `astroconda` team uses `conda config --add` in their installation instructions here: https://astroconda.readthedocs.io/en/latest/installation.html#configure-conda-to-use-the-astroconda-channel so it would mean that we wouldn't match with their instructions anymore.

@mperrin let me know what you think and I can open a PR

**Comment by mperrin** [comment]
So we currently follow what the astroconda instructions say to do? In that case I don't understand @PatrickOgle's statement that this breaks the ability to create new conda environments. Surely it's not the case that the regular astroconda instructions prevent the creation of new conda environments. Right?!?

**Comment by shanosborne** [comment]
That's what it looks like to me. The astroconda docs say that users should "append" the astroconda channel, but the code they give is `conda config --add`. Maybe the astroconda team has gotten comments like this before, or maybe this issue is a rare event and is just a problem within `conda` - I'm really not sure.

**Comment by shanosborne** [comment]
@PatrickOgle - thinking about this more, I think your issue is more related to a possible bug in your conda setup or maybe a problem with astroconda being added to the channels. I can open up an issue with astroconda and ask them if they've seen this behavior before from people following their installation instructions

**Comment by rendinam** [comment]
@PatrickOgle , could you please provide the version of conda you are using? I am unable to reproduce the error on Linux with conda `4.8.4` or Macos using conda `4.8.0`. I have verified that having the Astroconda channel as highest priority in the list of channels along with `conda-forge` and the defaults channel entries does not prevent the creation of new environments, including a `webbpsf` environment.
```
$ conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'
--add channels 'https://ssb.stsci.edu/astroconda'   # highest priority
```

If your conda version is older than `4.8.0` I would recommend updating it to a more recent version and trying to create the environment again.
This may be done with `$ conda update conda` from the base environment.

If that does not improve matters, I would then suggest renaming your existing conda installation directory and starting anew with a fresh installation of conda from a recent installer.

**Comment by PatrickOgle** [comment]
conda version : 4.8.4
MacOS

**Comment by mperrin** [comment]
@shanosborne wanted to check in and see if you think there's any more needed on this, since you were recently updating install docs in one of the other PRs. Is there more to do on this particular issue at this point?

**Comment by shanosborne** [comment]
@mperrin This problem was more related to astroconda than to webbpsf. I opened an issue in astroconda-contrib and never head back, but either way I think this ticket can be closed.
