### ISSUE TITLE
move_segment_local discards translation

### ISSUE THREAD

**Issue by AldenJurling** [spacetelescope/webbpsf#394]
The translation handling in [move_seg_local()](https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/opds.py#L1427) doesn't look correct to me:
``` python
        # Handle displacements. First special handling for radial vs x/y trans to allow both ways.
        if radial is None:
            if xtrans is None and ytrans is None:
                radial = 0
            else:
                if 'A' in segment:
                    radial = -1 * ytrans
                elif 'B' in segment:
                    radial = 1 * ytrans
                else:
                    radial = 1 * xtrans
        else:
            if xtrans is not None or ytrans is not None:
                raise RuntimeError("Cannot specify x/ytrans and radial at the same time.")

        vector = np.asarray([piston, radial], dtype=float)
         ... # skip
        # Ordering = xtilt, ytilt, piston, clocking, rad trans, roc
        update_vector = [tilts[0], tilts[1], vector[0], tilts[2], vector[1], roc]
```

For a call like this:
``` python
ote.move_seg_local('A1', xtrans=1.0, ytrans=2.0) 
```
`radial` is `None`, so we'll take the first branch, and `xytrans` and `ytrans` are not `None`, and we're an `A` segment, so we'll do
``` python
                    radial = -1 * ytrans
```
and discard `xtrans`. 
I cant see any path through the formation of `update_vector` where'd pas both the x and y translation arguments through.

I encountered this via using the method as a way to extract `webbpsf` influence functions, which got me this (for one segment)

![seg_infl](https://user-images.githubusercontent.com/5366461/101680296-79205200-3a2e-11eb-9a0a-e6d331056ae5.png)

which shows no influence for x translation. 

I'm guessing this is one for @mperrin.

**Comment by AldenJurling** [comment]
Note that [move_sur()](https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/opds.py#L1745) takes this code path. I'm not sure if that method is in the rehearsal sim path for OTE  or not.

**Comment by mperrin** [comment]
Hi @AldenJurling, you're 100% correct there is no code path through this function that passes both x and y translation through. But there's a deeper reason rather than what's just in the code in this function: the azimuthal translation degree of freedom doesn't have any influence function model at all for the JWST WSS code. No influence for x translation, indeed. 

We never control this degree of freedom for JWST,  and there aren't any rows in Ball's influence function table for this, this degree of freedom literally does not exist in the WAS software in any fashion whatsoever.  So... not in the WAS influence function table, therefore no way to model this degree of freedom consistently with the rest (not without breaking the assumption of using precisely the WAS' influence function model data here in WebbPSF). The code in WebbPSF allows you to specify x-trans or y-trans as synonymous with radial (depending on which of A, B, or X segment types, each with their own differently rotated local coordinate system), but that's all. It's just the one underlying radial degree of freedom that is modeled. 

This is not how I would probably have designed the WSS; even if we're not controlling this degree of freedom nominally because it's degenerate with a combination of other degrees of freedom, I'd still have put a model for it into the influence function table. But I think the logic was that it's cleaner to leave out any model of the uncontrolled degree of freedom entirely.

**Comment by AldenJurling** [comment]
> But there's a deeper reason rather than what's just in the code in this function: the azimuthal translation degree of freedom doesn't have any influence function model at all for the JWST WSS code. 
> ... even if we're not controlling this degree of freedom nominally because it's degenerate with a combination of other degrees of freedom ... 
> 

Thanks @mperrin. Putting this together with the local influence function coordinate systems you sent separately here kicked my brain back into gear. 

![infl_coords](https://user-images.githubusercontent.com/5366461/101913529-1a271e00-3b91-11eb-87c4-ee7449928c7a.png)
 
If I'm thinking about this right: because the local coordinate system is constructed such that one translation degree of freedom is purely azimuthal and the other is purely radial, the azimuthal degree of freedom isn't just degenerate, its actually zero. Differential azimuthal motion of the segment is equivalent to clocking about the axis of the parent conic optic, which is an axis of symmetry of the conic of revolution, which has no impact at all.

When I first opened this issue I was picturing the local axes as all parallel but just translated around the aperture, which would give some segments six non-zero influence functions, but only five linearly independent ones. In which case you'd want them all in the table and then fix up the linear algebra for the control problem to get rid of the extra one. In this construction you don't have to do the linear algebra to get rid of that extra degree of freedom: you can just drop it entirely. That also helps to motivate the somewhat puzzling local coordinate definition, since defining them that way lets you do that. Though, if it was me, I would have made all of the local x-axes point along the polar coordinate theta direction and the all of the y axes point along the polar coordinate radial direction. 

Assuming that is all true, the `webbpsf` influence function extraction I plotted should be actually exactly correct.

**Comment by mperrin** [comment]
>  the azimuthal degree of freedom isn't just degenerate, its actually zero. 

Almost zero but not _quite_! At least, for finite non-infinitesimal moves.  The precisely zero mode is azimuthal translation plus a bit of clocking and radial translation. Together those three can indeed be clocking about the axis of the parent optic. That's what I was getting at with the statement about degeneracy with other modes.  But yes, to first order that simplifies to azimuthal translation.  So it's a weak but not precisely zero influence function. 

See also Gersh-Range and Perrin 2012, section 3.something, in which we work through this rigorously in terms of the hexapod degrees of freedom relative to the optical axis.  This could end up being super useful if we end up in the unfortunate scenario of losing an actuator at some point: in effect you can put all the hexapod position error into the rotate-around-parent-conic-axis, and get zero WFE impact from having a stuck hexapod leg.  The fact that there are only 5 linearly independent degrees of freedom is the key insight here, something which I credit Paul Lightsey for helping me realize back in 2011 or so.   I also think this is potentially a not-yet-pursued opportunity for dealing better with some workspace boundary issues, since in effect it gives a way to trade between clocking and radial translation if we run against the radial translation limit.

FYI there's a second linear model in WebbPSF, that Erin Elliot derived independently many years ago. This is mostly not used for anything any more (though it's what we used in that paper I just mentioned). That one does have the small but nonzero term for azimuthal translation in it. This is what I was referring to when I said we could potentially add a model for this term into WebbPSF but not from a consistent source as the rest. 

And yes, the rotational symmetry around the parent axis also helps motivate the local coordinate definition -- along with the actual physical symmetry of making all the segment hexapod hardware the same way, so all the A segments are physically interchangeable and so on. I do not know exactly what led to the different local axes choices for As, Bs, and Cs though - it may have something to do with packaging constraints, maybe for mounting the segments in the wings, but if I ever knew the details I don't recall now. We'd have to ask Scott or Paul.

**Comment by AldenJurling** [comment]
> Almost zero but not quite! At least, for finite non-infinitesimal moves.

Oh, certainly: I was speaking in the sense of infinitesimal moves and partial derivatives, and interpreting the influence functions as partial derivatives. At the nominal segment location, the partial derivative of wavefront with respect to segment translation is zero. For any finite translation, there will be a small contribution. Which, I think could be shown via some trigonometry to be quadratic in the translation distance.  Presumably all of the degrees of freedom have small second order responses and mixed-partial second order coupling terms. 

This is an example of where the sense of first-orderness can be ambiguous: if you interpret it as "find the linear term and keep that", then that response is zero. If you interpret it "find the first non-zero term in the Taylor expansion and keep that", then its a non-zero quadratic thing, where all of the degrees of freedom's first term would be the (non-zero) linear one. 

I *think* in the WFSC context it would only make sense to add in the second order translation effect if we had reason to think it becomes significant much faster than the other second order terms that also aren't modeled in the influence functions. Though this one was is more tractable then some others in the sense that you could obtain via trigonometric manipulation of the other influence functions, rather than by ray tracing, as you'd have to do for something like the second partial derivative of wavefront with respect to segment piston. 

> FYI there's a second linear model in WebbPSF, that Erin Elliot derived independently many years ago. This is mostly not used for anything any more (though it's what we used in that paper I just mentioned). That one does have the small but nonzero term for azimuthal translation in it

Presumably the non-zero value depends on the choice of finite step size Erin used to construct that linear model. 

> See also Gersh-Range and Perrin 2012, section 3.something,

Thanks for the reference, I was familiar with the basic idea of the work, which we've discussed at a few other events, but hadn't read the paper previously. Nice study, and an impressive result.

**Comment by mperrin** [comment]
No need for action on this issue - all is as it should be, as discussed back in December. Closing.
