### ISSUE TITLE
Difference in assumed position between PySIAF and default detector position.

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/webbpsf#401]
I noticed there is a half-pixel between the default detector position (e.g. NRCA3_FULL is set to 1024, 1024) and the PySIAF position, which puts it a (1024.5, 1024.5).  This was noted while working on the OTE Secondary Mirror Influence Function, where we define a `ote_control_point` (e.g. NRCA3_FULL, calculated using PySIAF's `reference_point`), and determine the angular separation to a field point (determined using PySIAF's `sci_to_tel(1024, 1024)`). If the field point is also NRCA3_FULL, then the angular separation is small but non-zero, whereas we expect it to identically zero.

**Comment by mperrin** [comment]
Looking at this a bit closer, it's actually just that the detector position is always rounded to integer pixels: 
```
        self._detector_position = (int(position[0]), int(position[1]))
```

I think when I originally wrote that code, I didn't think through whether or not there was a use case for having it as floats or not. In particular, these parameters don't control the sub pixel position of the source. While the PSF location can indeed be a sub pixel position, set by the source offset parameters, in some sense the subarray that webbpsf computes out of the full detector array is inherently only ever on integer pixels.

**Comment by mperrin** [comment]
Not sure if any action is needed on this. I think not, unless we can identify some concrete impact of this that can't be worked around otherwise. I think the detector_position is intentionally always integer pixels and probably should remain that way?   Though perhaps we could convert it to float without any issue. 

Perhaps what's needed is documentation to note the semantics of the detector_position attribute? It's a little subtle in that it's used to (in effect) position the subarray that webbpsf simulates relative to the full detector. But it doesn't affect the subpixel centering of the output PSF. For instance if you were to increment the detector position by half a pixel, currently it would not shift the PSF by half a pixel. 

I am inclined to mark this as "won't fix" compared to other priorities... but please let me know if you think otherwise @Skyhawk172

**Comment by Skyhawk172** [comment]
No objection.  The impact from the SM IF is negligible at the half-pixel level, no doubt about it.
