### ISSUE TITLE
Roman Coronagraph Instrument

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#445]
Rename CGI to "Roman Coronagraph Instrument" (Roman team request)

**Comment by mperrin** [comment]
@ojustino I found this old Roman issue which Robel did not deal with, asking to rename the class in WebbPSF away from "CGI". I don't know if this is a priority for right now or not (we barely support the Roman Coronagraph in this package), but I do know they've tried to deprecate the use of 'CGI'. 

It would be straightforward to refactor this to rename the instrument class from `CGI` to `RomanCoronagraph` or `RomanCoronagraphInstrument`. 

@douglase, @nasavbailey -  any opinions on this?

**Comment by ojustino** [comment]
@mperrin I haven't touched any code related to the coronagraph, but a rename would be a quick, cosmetic fix.

One thought from a usage perspective is that the proposed names here are closer in style to the telescope-focused instrument classes (e.g., `JWInstrument`, `RomanInstrument`) than the instrument-focused classes that inherit from them (e.g., `MIRI`, `NIRCam`, `WFI`). I assume most users would know which category it falls into, but I wanted to check if the consistency in naming was important.

**Comment by nasavbailey** [comment]
Thanks for changing away from CGI.  RomanInstrument + Coronagraph or RomanCoronagraph are both fine, or if there's another permutation that fits with your naming convention, that's good too. It's fine to use just Coronagraph instead of Coronagraph Instrument when there's a desire for a shorter name.

**Comment by robelgeda** [comment]
Might be worth calling it RCI given the other acronyms.

**Comment by mperrin** [comment]
Thanks Robel for the suggestion, but as far as I know it turns out nobody ever calls it "RCI", so it would likely add confusion rather than add clarity to use that here... We're going to go with "RomanCoronagraph" in this case, following Vanessa's advice above.

**Comment by nasavbailey** [comment]
Good call on RomanCoronagraph. Thanks! Unfortunately, there is no officially-sanctioned abbreviation. CGI can still pop up occasionally when it's really impossible to fit the full word, but otherwise we're supposed to stop using it. I probably have some lingering repos that are in violation myself...
