### ISSUE TITLE
Add WFI to minimal data files?

### ISSUE THREAD

**Issue by ojustino** [spacetelescope/webbpsf#470]
Currently, `make-minimal-datafiles.py` only supports the following instruments:
`insts = ['FGS', 'NIRCam', 'NIRSpec','NIRISS','MIRI']`

Should WFI be included in the list?

**Comment by mperrin** [comment]
No change is needed, except maybe some clarifying comments in that script. That list of instruments isn't the list of instruments that is included; rather it's a list that gets iterated over (just below in that script) to trim out extra OPD files per each instrument. That's only needed on the JWST side because Roman doesn't have multiple OPDs in the models. 

If you look in the actual file `minimal-webbpsf-data.tar.gz` that's output, it does include the WFI data. Which is good, or else none of the WFI tests would pass on the CI builds! :-)
