### ISSUE TITLE
LRS Grating -> Prism

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/webbpsf#477]
This may be irrelevant to the code, but I wanted to flag that the MIRI LRS does not have gratings, it uses a double prism for dispersion. I'm only just digging into the code to see how it works exactly for LRS, so maybe this is just a vocabulary issue that has no impact on the code (as you don't model the dispersion), but I wanted to flag it in case you had made any grating-specific assumptions.

**Comment by mperrin** [comment]
Thanks @skendrew - I think you're correct this is a vocabulary issue with no impact on the code. Should be easy to fix and we will do so. 

I'll be happy to discuss how the LRS PSF is modeled if you have any questions, and would be glad to take any suggestions for improvements, for sure! :-)

**Comment by mperrin** [comment]
Having looked at the code now I can confirm it doesn't have any impact at all on the optical calculations. It's just a matter of what is the string value to set `miri.filter` equal to in order to invoke the model for the LRS pupil stop at the filter wheel. 

If you concur I'll make that just `"P750L"` rather than `"P750L LRS grating"`?  (The existing, incorrect string with "grating" will also remain as an option for back-compatibility so as not to break any existing code that might use that string).

**Comment by skendrew** [comment]
That works, thanks for looking into it!
