### ISSUE TITLE
MIRI Lyot focal plane mask seems incomplete

### ISSUE THREAD

**Issue by ccossou** [spacetelescope/webbpsf#481]
I've tried to make an attenuation map of all MIRI coronagraphs by moving a source position in each and every pixels of the detector for each coronagraphs.

For the Lyot Coronagraph, I ended up with a weird map, the "vertical bar" (for lack of a better word) was not going from top to bottom, but rather a small box around the center. 

Maybe I'm missing something in my input parameter that show there, though.
I've attached my end result to show you what I mean.

![ds9](https://user-images.githubusercontent.com/3242621/130762903-3c7021de-3ee9-4ab3-8082-178de16661f7.png)

**Comment by mperrin** [comment]
Hi @ccossou, good catch. I agree this is not as intended! I think you may be the first person to do full field of view sims for this coronagraph and thus encounter this issue. 

I looked at this briefly and realized the issue is that the poppy.BarOcculter class has a default size of 10 arcsec, and the use of this in the MIRI clas doesn’t specify any other length. It will be easy to fix this with a change to this line:
https://github.com/spacetelescope/webbpsf/blob/502b1877e0c6fe099e55d1bbd5539a2435d9fcb3/webbpsf/webbpsf_core.py#L1469

Try adding `height=32` to that line in your local copy of webbpsf. I think that will yield better results. I would try this now myself but I’m on holiday for the rest of August so I won’t be able to test prior to early September. Let me know if that improves the results. Thanks.

**Comment by JarronL** [comment]
Thought I had made a similar PR earlier this year, but apparently it never got submitted. We found the same issue when developing the `webbpsf_ext` package for use with MIRISim. Indeed, adding `height=31` to extend the bar to the edge of the field was the solution. If you would like, @mperrin, I can make the pull request.

**Comment by JarronL** [comment]
Add pull request #482.

**Comment by ccossou** [comment]
Juste a note to confirm that this fixes the issue, and the bar is extended over the full FoV with the fix (though I used height=32)
