### ISSUE TITLE
minor: docs rendering issue

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#583]
Something changed in the CSS or other style display for the documentation, such that bullet point lists no longer show any bullet symbols. For instance see https://webbpsf.readthedocs.io/en/latest/relnotes.html 

This is just cosmetic but it does seem to make it harder to read.

**Comment by ojustino** [comment]
I believe this is because of a problem with the `stsci_rtd_theme` package that's used to control CSS settings. `jwst`'s docs have [~the same issue~](https://jwst-pipeline.readthedocs.io/en/latest/jwst/introduction.html#output-file) ([updated link](https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/input_output_file_conventions.html)).

I reported this issue at spacetelescope/stsci_rtd_theme#19 and proposed a fix at spacetelescope/stsci_rtd_theme#20, but I'm not sure what the turnaround time is for a review. A temporary solution is to manually replace each `*` with a bullet character (`\•`), but it's tedious.

**Comment by ojustino** [comment]
The maintainers of `stsci_rtd_theme`accepted the fix in spacetelescope/stsci_rtd_theme#20 several months ago. They haven't done another release since the PR was merged, so we may need to specifically install the version on `main` in order for the `webbpsf` docs to render properly again.

**Comment by ojustino** [comment]
Now that version 1.0.1 of `stsci_rtd_theme` is out, this issue should be moot. Bullets are functional again in the documentation.
