### ISSUE TITLE
photutils GriddedPSFModel now supports different oversampling in each dimension

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/webbpsf#782]
This is just a heads up. I'm not sure if this will necessitate any changes to WebbPSF, but I just ran into an issue in Mirage:

In [version 1.10.0 of photutils](https://github.com/astropy/photutils/blob/main/CHANGES.rst#1100-2023-11-21) (released 21 Nov 2023), the GriddedPSFModel's oversampling factor has changed from being an integer to a numpy array, so that oversampling can be different in each of the x/y dimensions. 

In Mirage, we have a line that divides the PSF array size by the oversampling factor. This line crashed when the oversampling changed to an array.

I know that WebbPSF stores the oversampling factor in a header keyword. I'm guessing that assumes an integer for the oversampling value.

**Comment by mperrin** [comment]
So far this does not appear to be an issue, as far as I can tell.  WebbPSF does store the oversampling factor in the header keyword, but it does so using its own value from within the WebbPSF calculation output, which by construction is a scalar. 

Since we haven't heard any actual reports of this being a problem, and all the test suite passesss with photutils 1.10 (and 1.11 now), I think we can safely mark this closed. 

Thanks for the heads up in any case!
