### ISSUE TITLE
Update box URL to data archive in Actions workflows/download_data.yml

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/webbpsf#949]
romancal is using `download_data.yml` to generate a webbpsf data cache object:

https://github.com/spacetelescope/romancal/blob/5c515b8a739894116866ee2824474ac4ca71a60e/.github/workflows/data.yml#L16

Unfortunately we are receiving the following error in our CI test runs:

```
E               OSError: WebbPSF data package has version 1.4.0, but 1.5.0 is needed. See https://webbpsf.readthedocs.io/en/stable/installation.html#data-install for a link to the latest version.
E               
E                ***********  ERROR  ******  ERROR  ******  ERROR  ******  ERROR  ***********
E                *                                                                          *
E                *  WebbPSF requires several data files to operate.                         *
E                *  These files could not be located automatically at this time, or this    *
E                *  version of the software requires a newer set of reference files than    *
E                *  you have installed.  For more details see:                              *
E                *                                                                          *
E                *        https://webbpsf.readthedocs.io/en/stable/installation.html        *
E                *                                                                          *
E                *  under "Installing the Required Data Files".                             *
E                *  WebbPSF will not be able to function properly until the appropriate     *
E                *  reference files have been downloaded to your machine and installed.     *
E                *                                                                          *
E                ****************************************************************************
```

The `default` URL points to an archive different than the one shown on RTD (https://stsci.box.com/shared/static/qxpiaxsjwo15ml6m4pkhtk36c9jgj70k.gz):

https://github.com/spacetelescope/webbpsf/blob/207f724a881a224225f2e57243cefa09ffe4c04b/.github/workflows/download_data.yml#L34

cc @mairanteodoro

**Comment by BradleySappington** [comment]
The default URL in RTD (https://stsci.box.com/shared/static/qxpiaxsjwo15ml6m4pkhtk36c9jgj70k.gz) is link to our latest full dataset: `webbpsf-data-LATEST.tar.gz`

The default link in the github workflow is the link to the latest minimal dataset (and has been, this hasn't changed).
`minimal-webbpsf-data-LATEST.tar.gz`

These links are unchanged (which is why we use the `LATEST` naming convention), however the information within them has changed.  It looks like romancal hasn't updated its cache data in a week:
https://github.com/spacetelescope/romancal/actions/workflows/data.yml

Please manually run the `download and cache` workflow to get the latest data and I believe your issue will be resolved.  Let me know how it goes!

**Comment by jhunkeler** [comment]
```
Cache saved with key: webbpsf-data-mini-1.5.0
```

That worked. Thank you!

**Comment by BradleySappington** [comment]
Fantastic, thanks for the verification! Closing out issue
